
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMAISMENOSleftVEZESDIVIDIRABRE_PAREN DIVIDIR FECHA_PAREN ID MAIS MENOS NUMERO VEZESexpressao : IDexpressao : NUMEROexpressao : ABRE_PAREN MAIS expressao expressao FECHA_PARENexpressao : ABRE_PAREN MENOS expressao expressao FECHA_PARENexpressao : ABRE_PAREN VEZES expressao expressao FECHA_PARENexpressao : ABRE_PAREN DIVIDIR expressao expressao FECHA_PAREN'
    
_lr_action_items = {'ID':([0,2,3,5,6,7,8,9,10,11,12,17,18,19,20,],[2,-1,-2,2,2,2,2,2,2,2,2,-3,-4,-5,-6,]),'NUMERO':([0,2,3,5,6,7,8,9,10,11,12,17,18,19,20,],[3,-1,-2,3,3,3,3,3,3,3,3,-3,-4,-5,-6,]),'ABRE_PAREN':([0,2,3,5,6,7,8,9,10,11,12,17,18,19,20,],[4,-1,-2,4,4,4,4,4,4,4,4,-3,-4,-5,-6,]),'$end':([1,2,3,17,18,19,20,],[0,-1,-2,-3,-4,-5,-6,]),'FECHA_PAREN':([2,3,13,14,15,16,17,18,19,20,],[-1,-2,17,18,19,20,-3,-4,-5,-6,]),'MAIS':([4,],[5,]),'MENOS':([4,],[6,]),'VEZES':([4,],[7,]),'DIVIDIR':([4,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressao':([0,5,6,7,8,9,10,11,12,],[1,9,10,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressao","S'",1,None,None,None),
  ('expressao -> ID','expressao',1,'p_expressao_id','grammar.py',21),
  ('expressao -> NUMERO','expressao',1,'p_expressao_numero','grammar.py',26),
  ('expressao -> ABRE_PAREN MAIS expressao expressao FECHA_PAREN','expressao',5,'p_expressao_mais','grammar.py',31),
  ('expressao -> ABRE_PAREN MENOS expressao expressao FECHA_PAREN','expressao',5,'p_expressao_menos','grammar.py',36),
  ('expressao -> ABRE_PAREN VEZES expressao expressao FECHA_PAREN','expressao',5,'p_expressao_vezes','grammar.py',41),
  ('expressao -> ABRE_PAREN DIVIDIR expressao expressao FECHA_PAREN','expressao',5,'p_expressao_dividir','grammar.py',46),
]
