
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_PAREN DIVIDIR FECHA_PAREN ID MAIS MENOS NUMERO VEZESexpressao : expressao MAIS termoexpressao : expressao MENOS termoexpressao : termotermo : termo VEZES fatortermo : termo DIVIDIR fatortermo : fatorfator : NUMEROfator : IDfator : ABRE_PAREN expressao FECHA_PAREN'
    
_lr_action_items = {'NUMERO':([0,6,7,8,9,10,],[4,4,4,4,4,4,]),'ID':([0,6,7,8,9,10,],[5,5,5,5,5,5,]),'ABRE_PAREN':([0,6,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,4,5,12,13,14,15,16,],[0,-3,-6,-7,-8,-1,-2,-4,-5,-9,]),'MAIS':([1,2,3,4,5,11,12,13,14,15,16,],[7,-3,-6,-7,-8,7,-1,-2,-4,-5,-9,]),'MENOS':([1,2,3,4,5,11,12,13,14,15,16,],[8,-3,-6,-7,-8,8,-1,-2,-4,-5,-9,]),'FECHA_PAREN':([2,3,4,5,11,12,13,14,15,16,],[-3,-6,-7,-8,16,-1,-2,-4,-5,-9,]),'VEZES':([2,3,4,5,12,13,14,15,16,],[9,-6,-7,-8,9,9,-4,-5,-9,]),'DIVIDIR':([2,3,4,5,12,13,14,15,16,],[10,-6,-7,-8,10,10,-4,-5,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressao':([0,6,],[1,11,]),'termo':([0,6,7,8,],[2,2,12,13,]),'fator':([0,6,7,8,9,10,],[3,3,3,3,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressao","S'",1,None,None,None),
  ('expressao -> expressao MAIS termo','expressao',3,'p_expressao_mais','grammar.py',6),
  ('expressao -> expressao MENOS termo','expressao',3,'p_expressao_menos','grammar.py',10),
  ('expressao -> termo','expressao',1,'p_expressao_termo','grammar.py',14),
  ('termo -> termo VEZES fator','termo',3,'p_termo_vezes','grammar.py',18),
  ('termo -> termo DIVIDIR fator','termo',3,'p_termo_dividir','grammar.py',22),
  ('termo -> fator','termo',1,'p_termo_fator','grammar.py',26),
  ('fator -> NUMERO','fator',1,'p_fator_numero','grammar.py',30),
  ('fator -> ID','fator',1,'p_fator_id','grammar.py',34),
  ('fator -> ABRE_PAREN expressao FECHA_PAREN','fator',3,'p_fator_parenteses','grammar.py',38),
]
